### ISSUE TITLE
Nothing is injected in the HTML

### ISSUE THREAD

**Issue by k-vyn** [icelam/html-inline-script-webpack-plugin#353] opened 2022-03-28 06:31 UTC
## Environment and package version

Webpack 5.70.0
HTML Inline Script Plugin 3.0.0

## Reproduction link / code sample

It's a vanilla html file with some react. 

```
  plugins: [
    new HtmlWebpackPlugin({
      template: './apps/figma/src/ui.html',
      filename: 'ui.html',
      chunks: ['ui'],
      inject: 'body',
    }),
    new HtmlInlineScriptPlugin({scriptMatchPattern: [/ui.tsx/]}),

    new CopyWebpackPlugin({
      patterns:[
        { from:path.resolve(__dirname, "./src/root"), to:"./"}
      ]
      })
  ],
```

## Steps to reproduce

I'm running this with a build script inside a NX mono repo v13.9.2

## What is expected?

```
<h2>Shape Creator</h2>
<p>Count: <input id="count" type="number" value="5"></p>
<button id="create">Create</button>
<button id="cancel">Cancel</button>
<script>

document.getElementById('create').onclick = () => {
  const textbox = document.getElementById('count');
  const count = parseInt(textbox.value, 10);
  parent.postMessage({ pluginMessage: { type: 'create-shapes', count } }, '*')
}

document.getElementById('cancel').onclick = () => {
  parent.postMessage({ pluginMessage: { type: 'cancel' } }, '*')
}

</script>
```

## What is actually happening?

```
<!DOCTYPE html>
<html lang="en">
  <head><base href="/">
  </head>
  <body>
    <div id="react-page"></div>
  </body>
</html>
```

**Comment by icelam** [comment] 2022-04-28 12:27
@k-vyn Sorry for the late reply, I hope you have resolve your issue already. If not, below is the some recommendation you can try: 

1. You may want to check and confirm the `chunks: ['ui'],` option defined in `HtmlWebpackPlugin` is correct or not. Since the output HTML code you provided in the "What is actually happening?" section doesn't even have a `<script>` tag inside. A wrongly defined chunk name might prevent a script from being injected. Check the [official documentation](https://github.com/jantimon/html-webpack-plugin#options) for usage details.
2. After viewing the webpack configutation code snippet you provided in the "code sample" section, I am suspecting there might be a mistake in the `scriptMatchPattern`. The `scriptMatchPattern` only matches output files emitted by webpack, that means usually a matching filename will ends with `.js` instead of `.tsx` as they have been compiled.

Let me know if the above recommendation helps or not.

**Comment by jincheny** [comment] 2022-07-18 14:11
@icelam Hello, I have a similar problem.

### Environment and package version
webpack 5.73.0
html-webpack-plugin 5.1.0
html-inline-script-webpack-plugin 3.0.0

```
plugins: [
  new HtmlWebpackPlugin({
        title: projectName,
        favicon: './src/assets/favicon.ico',
        template: './webpack/template/index.html',
        filename: 'index.html',
        vendors: '',
        chunksSortMode: 'manual',
        chunks: ['vendors', 'index'],
  }),
  
  new HtmlInlineScriptPlugin({
      scriptMatchPattern: [/runtime~.+\.js$/],
  }),
]
```

**Comment by icelam** [comment] 2022-07-23 09:41
@jincheny I don't have enough information to reproduce the issue, it would be good if you can provide me a sample repository.

**Comment by jincheny** [comment] 2022-07-23 16:41
@icelam Please look at the files in the zip. Is this enough information? thank you.
[webpackConfigure.zip](https://github.com/icelam/html-inline-script-webpack-plugin/files/9174178/webpackConfigure.zip)

**Comment by icelam** [comment] 2022-07-24 06:50
@jincheny Thanks, this is really helpful. I have identified the root cause where the `@` symbol in the script name is being encoded to `%40`, which makes one of the checking fails.

https://github.com/icelam/html-inline-script-webpack-plugin/blob/636627b2602d98cc3f0f96deb9f04242555cb74d/src/HtmlInlineScriptPlugin.ts#L74

I will fix the issue and publish a new version probably within this week. Meanwhile, a possible workaround would be avoid using `@` symbol as part of script name:

```diff
module.exports = merge(C, {
  mode: 'production',
  output: {
    path: path.resolve('./dist'),
    publicPath: '/',
-    filename: `js/[name]@[contenthash:12]-v${version}.js`,
-    chunkFilename: `js/[name]@[contenthash:12]-v${version}.js`,
+    filename: `js/[name]-[contenthash:12]-v${version}.js`,
+    chunkFilename: `js/[name]-[contenthash:12]-v${version}.js`,
  },
```

**Comment by icelam** [comment] 2022-07-24 10:00
@jincheny The fix has been released in version 3.0.1, let me know if it solves your issue.

**Comment by jincheny** [comment] 2022-07-24 14:15
@icelam Both methods can solve this problem. Thank you very much.

**Comment by icelam** [comment] 2022-07-24 14:59
@jincheny You're welcome.

@k-vyn I am closing this issue since it is more likely to be a misconfiguration on the webpack config. If my above suggestion does not help, you are welcomed to open the issue again.

**Closed by icelam** 2022-07-24 14:59 UTC
